### ISSUE TITLE
Abandoned project?

### ISSUE THREAD

**Issue by harbaum** [ftCommunity/robo-blocks#1]
This project did not make any progress for over three years and imho has never reached a usable state. Would you consider moving this to your personal account?

**Comment by rkunze** [comment]
That's entirely your fault, because Brickly is good enough :-)

I've archived the project for now (so I can still answer the ticket), but I am also OK with deleting it.

**Comment by harbaum** [comment]
I just noticed that there are quite many mainly unused repositories so i thought it might make sense to clean up a little bit. Thanks a lot.
